{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.10.0-alpha01"
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-mingwX64Main-2.10.0-alpha01.klib",
          "url": "../../navigation-runtime-mingwx64/2.10.0-alpha01/navigation-runtime-mingwx64-2.10.0-alpha01.klib",
          "size": 124286,
          "sha512": "0c965c0305fadb470abd0be780c3cd28d167c068377a8f1139159fb896998357fb033fc3b9ef3a65c7d8eb6b5b3477da6409b17669906994158a42e92657849e",
          "sha256": "4491c8b657a27a287bdbf6488f7156a9799c8372a9b590a6073cee13cc4c0ef9",
          "sha1": "bf6511aba91798663cb2357131e553975536e7e4",
          "md5": "f59a0d8fedbf890fa4401be0ec01fa51"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-mingwx64-2.10.0-alpha01-sources.jar",
          "url": "../../navigation-runtime-mingwx64/2.10.0-alpha01/navigation-runtime-mingwx64-2.10.0-alpha01-sources.jar",
          "size": 44986,
          "sha512": "356f994f576b5ab568a584e1a09dce45ca22cb889099cc907b5945fca33d42b85358c7b5c0f8a5b3c1b1e500b3b68e44729014ed61567a75faaad356f594c08c",
          "sha256": "37f8b5f2060f301e372a333f8a416cbb5ec340c97a37578022d3cfe47789586f",
          "sha1": "855681e431e0ccd5749ab582fd9f2624e9f519d8",
          "md5": "e78d3275544c67e6e0a44bb16ed2b410"
        }
      ]
    }
  ]
}