{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate-compose/1.5.0-alpha01/savedstate-compose-1.5.0-alpha01.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate-compose",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "savedstate-compose is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-compose-mingwX64Main-1.5.0-alpha01.klib",
          "url": "savedstate-compose-mingwx64-1.5.0-alpha01.klib",
          "size": 7459,
          "sha512": "6ebe3b67d9c9ff4b382202531ed20ddeec2e4074d99c6d6c62d4eeeee37ea6330880da55e0aabc567e63efe4ee58a906cbf6d256f27bf5ba2b0405f404135a07",
          "sha256": "a9d4fbb11be067b233b1cc32142151790992ff9a7d76538f1280f177d29cfd18",
          "sha1": "3771a0ece8d42e1e76d3a0f063a20b790f6fa9f4",
          "md5": "d88771ed7f52ee63d2308a4f1baf3120"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "savedstate-compose is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-compose-mingwx64-1.5.0-alpha01-sources.jar",
          "url": "savedstate-compose-mingwx64-1.5.0-alpha01-sources.jar",
          "size": 5342,
          "sha512": "d74c63798658579728f55ac0b9cd9f1ef1d2a498c74af6a8d5b3773d077d30adde2b7d73932595d7bcf5f0f6de1cdce6086d33ddc24bb9027afe7ac249bb4b66",
          "sha256": "93fcc9270d4cd025eadbddc47274307084bb70d42714969b789af630984d55ad",
          "sha1": "01e5665efa5fc3556fa8f0e33fc9c2c09d8df781",
          "md5": "674650d67a947030544381fda5399234"
        }
      ]
    }
  ]
}