{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-core/1.7.3/material-icons-core-1.7.3.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-icons-core",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-mingwx64",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-mingwX64Main-1.7.3.klib",
          "url": "material-icons-core-mingwx64-1.7.3.klib",
          "size": 452700,
          "sha512": "8387be26180eb0ca6949759633a158add90d6a5ba69726f0fdc5ecaf75f17eae78eb4462a6201ec6240686f6d94676b0cbe55cdb146beb46988cc39336dda80a",
          "sha256": "0312a2b8cfe7a83d534bb187778c0dc287650042f30821c77c2409e7d255f1f5",
          "sha1": "9cc5f7772128b09805bef47fd098facd00ed0a2a",
          "md5": "902b657adafa6e3c85c8bfdbc5426c45"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-icons-core-mingwx64-1.7.3-sources.jar",
          "url": "material-icons-core-mingwx64-1.7.3-sources.jar",
          "size": 284048,
          "sha512": "2803312f6e4dfb1b2501b44f47eb72fd02212e41a18c5dcbec7b7e280612b486d23b72d50688a2fb3776b1582ae63ec923fd3f39bdbc4e951a779dc133495f64",
          "sha256": "b3f1be7fda4d13a6d938bb918275ddc143e9d6a2007727f284778480526f5f16",
          "sha1": "e518df0d8a19c3833f72a24ff667853015e340fd",
          "md5": "6f8dfe229b864de0e1deaa71ad0c1434"
        }
      ]
    }
  ]
}
