{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-common/2.10.0-alpha01/navigation-common-2.10.0-alpha01.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-common",
    "version": "2.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-mingwX64Main-2.10.0-alpha01.klib",
          "url": "navigation-common-mingwx64-2.10.0-alpha01.klib",
          "size": 333777,
          "sha512": "1a0a4776c955d22e85a976fac0121d40ec7292a9d0a5691618c7f2b22340f99521c46fe8d8e375c92902206d9957a67a5c26a99d81aa8689ff9fbc3d2f20a2e8",
          "sha256": "5f525378802919cf35190d2c7a3236f137372043841a55ba56100ef3f047a8e2",
          "sha1": "1748933293c6f41846e51b37acbdc7b8c11dbf06",
          "md5": "b54106c2e9a7479c9b1ce5dce333d6dd"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-mingwx64-2.10.0-alpha01-sources.jar",
          "url": "navigation-common-mingwx64-2.10.0-alpha01-sources.jar",
          "size": 111455,
          "sha512": "3325e4bc5a317fcb8013302165b2eadf067f7ae0b69afee75866e0254b36ef52a2becb93c27a858670ad23f021df07c51566f9a5dfd283a3f37925300eab45f7",
          "sha256": "fc22a8ebeb80470655000fb18be3d8101bba9546384e227d478a07f0b0981b09",
          "sha1": "19535c6e947043a0ac1f5335d94ffe8a427b71f3",
          "md5": "d6567cf1670d8fd197e4a0960a502724"
        }
      ]
    }
  ]
}