{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "1.11.0-alpha04"
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-mingwX64Main-1.11.0-alpha04.klib",
          "url": "../../runtime-mingwx64/1.11.0-alpha04/runtime-mingwx64-1.11.0-alpha04.klib",
          "size": 7517,
          "sha512": "1801720bb37de6b35c716e6d6a8350343587cb9e94747a2a15a6f188572ce4cd8988b133d87ab2f82ea06b9c9bd24dbdfd8c29bfc24c593bca57bd6a36958be8",
          "sha256": "17f6d33f5f0215d18cd57068aa5fb611ed63ac87a4c6f3118618f4e8cfb9a58e",
          "sha1": "7810357e03a279486154c6817ee32e25b10952b8",
          "md5": "824972a8f774a6b5981ab1cb39871a5b"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "../../runtime-mingwx64/1.11.0-alpha04/runtime-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 5458,
          "sha512": "c132cc206c2c0d1ac27b96f1e6c21d26e4e5267b2238fb6d0efdaa3d94472147fd1fe2c90a552831866efe84aa5d5faae4a8573a3af4ba3e3c43b32bec19c294",
          "sha256": "3f20e73dd171f53cbec1ebf7581e43d6fd0e36ab98fdc58cfa44c36e290c9408",
          "sha1": "84533f1542cca495cba9132ec7b0856e0656d0da",
          "md5": "1fcc0da41c14fc3a06905f01ee65017d"
        }
      ]
    }
  ]
}