{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-text/1.11.0-alpha04/ui-text-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-text",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.144.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-mingwX64Main-1.11.0-alpha04.klib",
          "url": "ui-text-mingwx64-1.11.0-alpha04.klib",
          "size": 867749,
          "sha512": "686633796b1fd6b990e56caaf3f303ec42ed8d4d8e1ffbe66cade8f0815484967b65e233e37ddeabcb46986a68a8512a0b4921b7b48bcb97f0cbd947552344cc",
          "sha256": "dcd44d1b3d8004f4153dfc1b0eea3a0a1d93d549df7ff7c1f5319d0dc3b5dacd",
          "sha1": "32ec707d98022f1cdcc8dc3b255d33febc57529e",
          "md5": "be95f51cba04b185192b2f017b53a252"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "ui-text-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 251336,
          "sha512": "aa57e7ec6cc3c1e2d01396a87c1a7b86d0b813d04a0b44b6142ee30411b372ea490ed361d673b2ab4861a1816734e51ed96e155337e666cdc79a329253738d04",
          "sha256": "aaf052985e137f4489466b2fc4497acadb16ed53c18ea10bac1c9be62227442c",
          "sha1": "c1a91ed86338d28fa6ef466f88b4d5f811175e8b",
          "md5": "e03388645a726423d6a9f4ffae5e2c29"
        }
      ]
    }
  ]
}