{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime-compose/2.11.0-alpha01/lifecycle-runtime-compose-2.11.0-alpha01.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-mingwX64Main-2.11.0-alpha01.klib",
          "url": "lifecycle-runtime-compose-mingwx64-2.11.0-alpha01.klib",
          "size": 7477,
          "sha512": "12b00f2ae77caba934c9d19df3eecd3ece6b97fdc519a5eeeed5fd07858053790f0a0da14f0b0be944459765986f77aa7836cd03f6a0820011effc10d1659a38",
          "sha256": "033a9353eb348068db09b8b1b19be4ed89eb3353aeee9bc39cf47ca4236a83ea",
          "sha1": "00b94946b8fbdf7ad0cdc48956eaa145755f04e0",
          "md5": "62a6b439c9d030644248c8c322cdb448"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-mingwx64-2.11.0-alpha01-sources.jar",
          "url": "lifecycle-runtime-compose-mingwx64-2.11.0-alpha01-sources.jar",
          "size": 5364,
          "sha512": "5e7e716da9238e8f8d6d0fbf9de0b9af144af97834201f3bfbdabd7da74cd0e783a48b060172179200f1ec48f7bf701ec9ed77a5f7362ba8a370e74633ff43d3",
          "sha256": "56cb226e051ef1d213c1cd8e4e3de1861a64455eafbe54c6a5ac10220f6898f9",
          "sha1": "7393e652a77f8a778d45c861ae90bede879dddbf",
          "md5": "73a83066a873ec427ba957b3233ff4ba"
        }
      ]
    }
  ]
}