{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/1.11.0-alpha04/animation-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-mingwX64Main-1.11.0-alpha04.klib",
          "url": "animation-mingwx64-1.11.0-alpha04.klib",
          "size": 467835,
          "sha512": "63cbdd80a31e750a73917c5dd2a15caf9cc51c562b4fa25dacc7aa7e69705e92446219cbc772ad5060e66316f0a3fc885b65f7f1d44e0b7ff4a9cd8ac5b42da2",
          "sha256": "7626af6039a1ed58879e0e40590886467c3581cdb778204cf0ad2dfc94535490",
          "sha1": "ee8b625db128495c0dd3ceb7aa5c595a7f659400",
          "md5": "7ee5369bbf9139b4c82c75c5f8c7ca08"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "animation-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 108534,
          "sha512": "8a098457c5497e7be58c3c3e9f5887ed2536e8eee36817af970675b46ab995cae229a7eda1e40615a32e851271d5ede89a6c093d094c58d54790e5d66a973a1f",
          "sha256": "6be5877f1eb142434dcdd1c4c8e8d9dc6af0e9b4fc6ab97ab08693b7bcfa5161",
          "sha1": "c63edcf0bd7dc49283a3faa8b7031f708f87cb62",
          "md5": "000ed8d5b46584ae320bb6efc6686f03"
        }
      ]
    }
  ]
}