{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix-navigation3-ui/0.9.0-f912a51a-SNAPSHOT/miuix-navigation3-ui-0.9.0-f912a51a-SNAPSHOT.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix-navigation3-ui",
    "version": "0.9.0-f912a51a-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "top.yukonga.miuix.kmp",
          "module": "miuix-shapes",
          "version": {
            "requires": "0.9.0-f912a51a-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-navigation3-ui-mingwX64Main-0.9.0-f912a51a-SNAPSHOT.klib",
          "url": "miuix-navigation3-ui-mingwx64-0.9.0-f912a51a-SNAPSHOT.klib",
          "size": 122420,
          "sha512": "bb1fbd1d6b59a93df466b94c517166abbe342726c19b50670fc84e05dd8631caf581a600727c1842b71e2029ff44550f0acbfe777beb06eb2cff125bc803eaba",
          "sha256": "6ee977005b39ea9e7e7c9e7f6669ca7d116a9e49c968a2aba3723ebee2af2ee8",
          "sha1": "20d4f38256746dde5033833ed74fe9991c9c3536",
          "md5": "2d1ea340cf61073d5b0064320396df50"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-navigation3-ui-mingwx64-0.9.0-f912a51a-SNAPSHOT-sources.jar",
          "url": "miuix-navigation3-ui-mingwx64-0.9.0-f912a51a-SNAPSHOT-sources.jar",
          "size": 31394,
          "sha512": "8291aff75c3f9f511c2c4a0ebc5905cdabcf3accc2cf401f645684ea6fe1ce1f12cf8146d5fe96f450f4604d49387ce54c7e6e9ff7cf10e148b8a154a565e6bf",
          "sha256": "23615fe3f3ff8dc99bc180cc255129c07e0c0100f05391675f865d81aa31d9ce",
          "sha1": "717e3decbfabd7c7bcc8aeade41b9bb22bd220b7",
          "md5": "d3f43961297e07b2599b31e768131864"
        }
      ]
    },
    {
      "name": "mingwX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "top.yukonga.miuix.kmp",
          "module": "miuix-shapes",
          "version": {
            "requires": "0.9.0-f912a51a-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-navigation3-ui-0.9.0-f912a51a-SNAPSHOT.kotlin_resources.zip",
          "url": "miuix-navigation3-ui-mingwx64-0.9.0-f912a51a-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 372,
          "sha512": "29face6a8b5b8802855394ff8d70f14903f8e6fa0bbd1665ebcb35f5b4370c6decc880da2bda2468040fab6d6d28a9db48f07b2f7fff872f25cddea24214557e",
          "sha256": "3f32491826b76ff223f0f8ccace68c9d5a5e5204a17de19a42b62339136cc846",
          "sha1": "6ea1d69cf412640104e09dfbde5a4f79603fbcc2",
          "md5": "700c1bd49329cf2aa032d47037dec489"
        }
      ]
    }
  ]
}
