{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-extended/1.7.3/material-icons-extended-1.7.3.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-icons-extended",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-mingwx64",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-mingwX64Main-1.7.3.klib",
          "url": "material-icons-extended-mingwx64-1.7.3.klib",
          "size": 22378445,
          "sha512": "b086418145b96f8a3e89ac04ec0554d80a004e2e0c2c444dbbd177561f7f0f6d525e1b212d4aebe8d48229349fca3fb4169be7da57ae34dcfd0c98a707fced8e",
          "sha256": "cc4899a0eb84e6e943a93941f2ad6ffb48903f323947e92ec3c751f03a47309f",
          "sha1": "7ff476693ff9fd2fb1cf01d2be81af7a2c278240",
          "md5": "66e09b5872f1173a3a2b6351afba135c"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-icons-extended-mingwx64-1.7.3-sources.jar",
          "url": "material-icons-extended-mingwx64-1.7.3-sources.jar",
          "size": 12080900,
          "sha512": "7f2bbc1c41ca471ed1ed724c3750c8d0a5c5c9656e2c3a8a4fd0198962d9ac1b14bef314e02a24b7851520366307de76c85e6e50f1452e0392262509562c0259",
          "sha256": "08fdc1986f45b0ffbb46aa0a920ec70b32b94addced2387d4f2cb6b202d4d510",
          "sha1": "4b060fbfd8e78ccbd33b895d28462f994f0745af",
          "md5": "d076166daedccc88532c9ec5b58ea9fd"
        }
      ]
    }
  ]
}
