{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-extended/1.7.3/material-icons-extended-1.7.3.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-icons-extended",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-mingwx64",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-mingwX64Main-1.7.3.klib",
          "url": "material-icons-extended-mingwx64-1.7.3.klib",
          "size": 22378636,
          "sha512": "3085a45c325adf68e5e44fecdd1273711a80bb400db0c34a8c1be07b4daee274a58ef026c7eed184c09a1d0fc1fac28a093e5bfc143e822effed738b0cb27e95",
          "sha256": "2e96086b686cdceaa8324677f4f2e704076a6444283c4ec8d1c01e6999fbd080",
          "sha1": "1ea11d4bd8966fb2a94c4f1f8a685c3a3fb3c4ce",
          "md5": "0218c3b796aecabbfb54d9502f98b292"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-icons-extended-mingwx64-1.7.3-sources.jar",
          "url": "material-icons-extended-mingwx64-1.7.3-sources.jar",
          "size": 12080900,
          "sha512": "7f2bbc1c41ca471ed1ed724c3750c8d0a5c5c9656e2c3a8a4fd0198962d9ac1b14bef314e02a24b7851520366307de76c85e6e50f1452e0392262509562c0259",
          "sha256": "08fdc1986f45b0ffbb46aa0a920ec70b32b94addced2387d4f2cb6b202d4d510",
          "sha1": "4b060fbfd8e78ccbd33b895d28462f994f0745af",
          "md5": "d076166daedccc88532c9ec5b58ea9fd"
        }
      ]
    }
  ]
}
