{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.11.0-alpha04/foundation-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.144.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-mingwX64Main-1.11.0-alpha04.klib",
          "url": "foundation-mingwx64-1.11.0-alpha04.klib",
          "size": 4290740,
          "sha512": "f2f64d5b86d38ccdb56af8507624de8009dbb5253a52157ce66d41898f87a9ffd112b011b042528272a1ce1cb5170a1c77b165c87005d6ac582360402f1647fc",
          "sha256": "89348cc5ad8aa87933f927c24507748a5e6484643b9a6fd89afc9e1c334dbe80",
          "sha1": "87f4f1a7260632017c5c4baa4c54711280489f61",
          "md5": "65c91ed20b0647fb01132877c38218b5"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "foundation-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 1176308,
          "sha512": "d84f2973882f49cf1fc49159e68f96f7062092bcfe606ea06d806519681a79dadc8a2d771e49d050e32ab87b9fbebf1f1ff6e3d114b22ca9dddd3e17dcbc4ad7",
          "sha256": "889e551abdfea0cc777f14e45393eb91f1728a7152c544d217363ea66d9ea694",
          "sha1": "30ab561ff0d7d7a44c3b36eaffa69b4ab9d9a555",
          "md5": "c28b13f449dd53b4e63ef30ff8603afc"
        }
      ]
    }
  ]
}