{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.11.0-alpha04/foundation-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.144.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-mingwX64Main-1.11.0-alpha04.klib",
          "url": "foundation-mingwx64-1.11.0-alpha04.klib",
          "size": 4289955,
          "sha512": "fc60dc613bceccfff2e0dad0936d1d64fef67a648b5a19dac48dc53dff5ac76b8d33956e505e7845b77cb81c875b4a6d12309a9162cc886345385c114f237448",
          "sha256": "0ad202bf65399b0aa77ab5295e84d66b23eb1a0e3d394deb4da01c1608bb2938",
          "sha1": "333b7bb9bd43a0e7e6103d9661c17a64e3e6274c",
          "md5": "c1f41736f52ede97390e86bd75cd4dc2"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "foundation-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 1175922,
          "sha512": "f130bc773ba71ed3630f2a26939977f6c8936f4d979de72af0c0721560bc1e42be10befb07535ba555a5cc96eebbc9e57da555e8deb06107897f465c96ce2b36",
          "sha256": "c25b43132f914ab8beb6b0753f897ad30a5f64faeb8424014a52d60d80ed7847",
          "sha1": "e51c682c51090d7443a184f7b1e28bb4d6b63872",
          "md5": "c900c47fe3a5988e502e417134c9d46d"
        }
      ]
    }
  ]
}