{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.11.0-alpha04/animation-core-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-mingwX64Main-1.11.0-alpha04.klib",
          "url": "animation-core-mingwx64-1.11.0-alpha04.klib",
          "size": 460447,
          "sha512": "bbefd4e373c10b334cec17278b348ae5dabf12d2b64cae607792a5b14947847edf661af89a77acefe1d8aed8da71ae08e6a78e22e12071f7d3be8fb2c9384da0",
          "sha256": "88567a25fac7e642e39861e3899113e5e5e878b483b64bbab6984009399cdc1a",
          "sha1": "93197d9c9f11b5e591c34208265ef720baee7e43",
          "md5": "bb46982693a494f12139a4aeb83a84fd"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "animation-core-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 119125,
          "sha512": "e8c45dedab429a8c7f902fa2b331d95f309e85e6e94ee10097d4d4888ec1f8e408b90888b23b0eb7b529219f4bde30c8474aebead0ee3cf3a78a8ba5e019e219",
          "sha256": "9e46045948c07016a2e36d9494e9b9f9f5a4bdf05c16ddc690769673bcba7fcc",
          "sha1": "8bb69707e9f7b0ef0d6d63ca6655c2c55db00b6e",
          "md5": "8c6aa84a345a840eb9cff21d5276efc5"
        }
      ]
    }
  ]
}