{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.11.0-alpha04/animation-core-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-mingwX64Main-1.11.0-alpha04.klib",
          "url": "animation-core-mingwx64-1.11.0-alpha04.klib",
          "size": 460447,
          "sha512": "bbefd4e373c10b334cec17278b348ae5dabf12d2b64cae607792a5b14947847edf661af89a77acefe1d8aed8da71ae08e6a78e22e12071f7d3be8fb2c9384da0",
          "sha256": "88567a25fac7e642e39861e3899113e5e5e878b483b64bbab6984009399cdc1a",
          "sha1": "93197d9c9f11b5e591c34208265ef720baee7e43",
          "md5": "bb46982693a494f12139a4aeb83a84fd"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "animation-core-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 119116,
          "sha512": "be1e9f352fe75646a89cf5a66fd9dec7c3a45f74df61fb77b17c6d108dfc8670c25c9501a4f85906a82936f859eb02f8c4c15ba25d16a309b1f15d9f5a757c22",
          "sha256": "6d1f02688b70a58fa609c323af70d85f0b4bbf230d4dc8f6ef02ad2ef0c6468a",
          "sha1": "cfc40bf62ffec1b46c42ca0a536d220ce55d36a1",
          "md5": "dc8522f953cd53c63db8c63d494c5817"
        }
      ]
    }
  ]
}