{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "1.11.0-alpha04"
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.144.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-mingwX64Main-1.11.0-alpha04.klib",
          "url": "../../ui-graphics-mingwx64/1.11.0-alpha04/ui-graphics-mingwx64-1.11.0-alpha04.klib",
          "size": 828071,
          "sha512": "530b30e595db286ab051c4e6205bffff75432f0bf64d6d31379349976fba09b470108fbfb7d3a68348702ad61256255c731ed0d869d332f52af01cdf4cccdc2c",
          "sha256": "d90d38e9c57285b81d52f5e6b0d84e85b31218a0f5acbe399dd9cf7b56221a00",
          "sha1": "ad58f76b4b8af14667f4e9f6b44d56578bede648",
          "md5": "9dde6eb3c65f6bd515105497aacd5206"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "../../ui-graphics-mingwx64/1.11.0-alpha04/ui-graphics-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 252488,
          "sha512": "7d8f58bdbd15f54164a03b62dcda15919004e5eb03031071b73ebf4b6f26aab346f2717bd1aea7793264ee2bb6d7438453efb636f743cb598e65640f714504a8",
          "sha256": "3fad5e6e3d821ff6b0135cc36b0d0ea4539049815d9de54cbeabcf7795cd53a0",
          "sha1": "5944ce343fc19c1799fb97b48ec3570c143ce112",
          "md5": "3fb60db0dd628b1e2b03f53e6d2fabc2"
        }
      ]
    }
  ]
}