{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.144.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-mingwX64Main-0.144.5.klib",
          "url": "../../skiko-mingwx64/0.144.5/skiko-mingwx64-0.144.5.klib",
          "size": 47211765,
          "sha512": "c299898a45301d868dbfc33c716833f5847702f9e4c87f0741dcb79afbc0ce99090f4ffe2f0f29ca81cefc39ea58c6789b916ccd2d755f071a8c23e639670ee5",
          "sha256": "878a2c8a78c68282d8ded4faa04e24bdfc59fc8903122e8bb7f6b045d1871e56",
          "sha1": "8a17d071eae277dcb27523e4cceadf520459eee9",
          "md5": "36b5385b02c38e8cfc3b88e8313c605b"
        },
        {
          "name": "skiko-mingwX64Cinterop-skikoMain-0.144.5.klib",
          "url": "../../skiko-mingwx64/0.144.5/skiko-mingwx64-0.144.5-cinterop-skiko.klib",
          "size": 3605,
          "sha512": "a41feaa16bf6307005903c68d9ce9b0fae39a54f4af2188c7298f1228cd55ff6a8499dd2f222462c723481d998481bdb14d0f8410c2b628bc534392cf4bf478d",
          "sha256": "7e498c6e0194665f040ef2b80b1d05e2b392e30cbd350e6e91764a3b9467a904",
          "sha1": "6a826aa5364b9ff2d61392d08880b972ff58f2b4",
          "md5": "d3fca6d2494f677e1455292ba6d0d8b7"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "skiko-mingwx64-0.144.5-sources.jar",
          "url": "../../skiko-mingwx64/0.144.5/skiko-mingwx64-0.144.5-sources.jar",
          "size": 263419,
          "sha512": "9d496c001c52b4860be806021bad41e14e50ef46b1e3a5de3abe449ed2435b945f80fae805c9ff024ce288cfaf08027ed37639f3d9722b5e6d92de44d6910f18",
          "sha256": "6187b9413588fa59af6546701aed302c446e04a2f17ae609e6cb070162c7de47",
          "sha1": "e25adee7955773ce4539bd3de8d7c15fdccf9753",
          "md5": "8cb05d28d49c5b2cf1badff2967c5066"
        }
      ]
    }
  ]
}