{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-compose",
    "version": "2.10.0-alpha01"
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.10.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-mingwX64Main-2.10.0-alpha01.klib",
          "url": "../../navigation-compose-mingwx64/2.10.0-alpha01/navigation-compose-mingwx64-2.10.0-alpha01.klib",
          "size": 123306,
          "sha512": "8f8a16372f3dc8ae7e6d0607e36c2c01791ec77d36377a077a4eb02fb16619c79e139373388f56cb4bf536ef12ef107e34abf104d5f1d1a3c9842be73f9903e9",
          "sha256": "55077dae722a53e0684cd71903c1c696957bb4dffc43038ba1b3008c050ccf5f",
          "sha1": "289cb0c8b61a4722297e744aa9af187e9568491f",
          "md5": "949ac57fb0f35da3728c12553c389c1e"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-mingwx64-2.10.0-alpha01-sources.jar",
          "url": "../../navigation-compose-mingwx64/2.10.0-alpha01/navigation-compose-mingwx64-2.10.0-alpha01-sources.jar",
          "size": 32768,
          "sha512": "9205f644c6c8506b366076b8345e0146ee2fd0853c8baf724aac73961e64fcf76502dfaff7256e662840e87bcbaf9f9f254627f625ab9fb38f6cedf6e38bf2e6",
          "sha256": "2ebdcfe2fe9a3951667519a8c5d12bcf1a641d92679eb0dbeb4773c8a8d91839",
          "sha1": "e246dcc061093f59d6ec0b40605bdc1f98223215",
          "md5": "d95f97604f817a15242b1f191a3bd11d"
        }
      ]
    }
  ]
}