{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui/1.11.0-alpha04/ui-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.11.0-beta02"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.144.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-mingwX64Main-1.11.0-alpha04.klib",
          "url": "ui-mingwx64-1.11.0-alpha04.klib",
          "size": 2959630,
          "sha512": "e6c3c1824923c8d0203b0f757325fcb5dfb5bfcc20015ddd95bb35b04be8255c4f8d68acd0d53990affb34ff3376cb0715619c640d4b0000cd99470c69910dd9",
          "sha256": "9778d8fbafb67a7b75c568a3e9efd50b4c496bba16c41266f596165667d6125a",
          "sha1": "fa1b319084fef14a956a5b0f241009d2dfdf55b7",
          "md5": "ff51b6d9048fe7e1aee2002dda03bda9"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "ui-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 811782,
          "sha512": "4171f0be791996e3d60649a5a48728c9c1ac1b51953829c9072940d26c1124855afb0452add30124abc7f3b60d802254f1c4e7b4a08e34ae452cee33d3b691a3",
          "sha256": "f47524434ac3992e5a12f74f2b6ca86844bfb709e7ac43520408c51e3ac02b5c",
          "sha1": "3e12e6426c4c16fabbe47c566f7a90ca8c0ab621",
          "md5": "9bb5d617df2b7c04bb4aaab0b2d97739"
        }
      ]
    }
  ]
}