{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skiko/0.144.5/skiko-0.144.5.module",
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.144.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-mingwX64Main-0.144.5.klib",
          "url": "skiko-mingwx64-0.144.5.klib",
          "size": 47241679,
          "sha512": "b19ab482eaca9d7af74ea49f22be81c655d6364a72d9cecf8f09beb5f61f1a3b1d43ae400332588085795440f2fc2afec1f493f0cadd3af5f2ef316000886185",
          "sha256": "6544fd13d18ba07f3e7f05d5de7bc474887979ef74cd8212cd123066ba8c8697",
          "sha1": "5a89f0826c03fd13ea6e227fac5b2b253d78f9bc",
          "md5": "0d94e72dc147e34a7a0b36cdc1cab2e6"
        },
        {
          "name": "skiko-mingwX64Cinterop-skikoMain-0.144.5.klib",
          "url": "skiko-mingwx64-0.144.5-cinterop-skiko.klib",
          "size": 3605,
          "sha512": "a41feaa16bf6307005903c68d9ce9b0fae39a54f4af2188c7298f1228cd55ff6a8499dd2f222462c723481d998481bdb14d0f8410c2b628bc534392cf4bf478d",
          "sha256": "7e498c6e0194665f040ef2b80b1d05e2b392e30cbd350e6e91764a3b9467a904",
          "sha1": "6a826aa5364b9ff2d61392d08880b972ff58f2b4",
          "md5": "d3fca6d2494f677e1455292ba6d0d8b7"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "skiko-mingwx64-0.144.5-sources.jar",
          "url": "skiko-mingwx64-0.144.5-sources.jar",
          "size": 268959,
          "sha512": "6673128169b64fe9b574e5588c9bcbb839e30d74ffc1027078a37ade82a3dfedc78aaa3669e70889651502309168f63f8d64915a3ffd60fb1b109d8506d4c704",
          "sha256": "f82f211f718335a0835e087fce0dc1a9f14f81b311fa03bee383a848b57fbe6d",
          "sha1": "00e4e13e727239060cb5c14be01d17521bd142f2",
          "md5": "efc6b1d22c1f33a22b68516174d7e7cf"
        }
      ]
    }
  ]
}
