{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skiko/0.144.5/skiko-0.144.5.module",
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.144.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-mingwX64Main-0.144.5.klib",
          "url": "skiko-mingwx64-0.144.5.klib",
          "size": 47169635,
          "sha512": "5fcbaac25c2546d8aadd7320f73790c114e2b2768c98c32aef4309e857aae0aa64d03c724f3a75ba2718a164fdfa56a7ef655878a2721a4f625fd318236e31e6",
          "sha256": "cf5049ed7c5a2d157be83a2b74c1aed961a576dbd9e99f10434b4f7899c0c236",
          "sha1": "663a54c82d9379cb35a589967a078ac406c70ed6",
          "md5": "d48fa81896cf67d99fcf2d62ec754f68"
        },
        {
          "name": "skiko-mingwX64Cinterop-skikoMain-0.144.5.klib",
          "url": "skiko-mingwx64-0.144.5-cinterop-skiko.klib",
          "size": 3602,
          "sha512": "6c5e598e7191f2c5ae30267d967dc73b0754b49444a1241228a7334470276226d51e1b6ef5e92d59a2b7398ffde31cb4e15d524e096dad719eb8c9e5f31a0d3e",
          "sha256": "c28d85d986ab4d6189952dd678c81ba735f942dbb1ff8cb3199bf13ed5d4f928",
          "sha1": "8ba83a62cbebeec7939f1135b45538f471b8858d",
          "md5": "46fb645c854ba066f3e9e56bedae1480"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "skiko-mingwx64-0.144.5-sources.jar",
          "url": "skiko-mingwx64-0.144.5-sources.jar",
          "size": 268959,
          "sha512": "6673128169b64fe9b574e5588c9bcbb839e30d74ffc1027078a37ade82a3dfedc78aaa3669e70889651502309168f63f8d64915a3ffd60fb1b109d8506d4c704",
          "sha256": "f82f211f718335a0835e087fce0dc1a9f14f81b311fa03bee383a848b57fbe6d",
          "sha1": "00e4e13e727239060cb5c14be01d17521bd142f2",
          "md5": "efc6b1d22c1f33a22b68516174d7e7cf"
        }
      ]
    }
  ]
}
