{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skiko/0.144.5/skiko-0.144.5.module",
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.144.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-mingwX64Main-0.144.5.klib",
          "url": "skiko-mingwx64-0.144.5.klib",
          "size": 47179279,
          "sha512": "7804086fe1105aa193942097a8d1d4cdba8d8b9f822a43e02999d81c4ab3a346bbf0e4d89db75a17898d47866d70a12e51594e0acb7ed207ed6105603106f1ac",
          "sha256": "78641725ba5c1b85b68131b7b2a05f98e6523c158845769a523dbe9e1160baeb",
          "sha1": "c68021dc919e3652f33cf6f95893f631ab325d59",
          "md5": "c925decaf05f086839476b2a3e5de123"
        },
        {
          "name": "skiko-mingwX64Cinterop-skikoMain-0.144.5.klib",
          "url": "skiko-mingwx64-0.144.5-cinterop-skiko.klib",
          "size": 3602,
          "sha512": "6c5e598e7191f2c5ae30267d967dc73b0754b49444a1241228a7334470276226d51e1b6ef5e92d59a2b7398ffde31cb4e15d524e096dad719eb8c9e5f31a0d3e",
          "sha256": "c28d85d986ab4d6189952dd678c81ba735f942dbb1ff8cb3199bf13ed5d4f928",
          "sha1": "8ba83a62cbebeec7939f1135b45538f471b8858d",
          "md5": "46fb645c854ba066f3e9e56bedae1480"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "skiko-mingwx64-0.144.5-sources.jar",
          "url": "skiko-mingwx64-0.144.5-sources.jar",
          "size": 269865,
          "sha512": "7aefdbbb2de1165ec039bff71351e123d341b59b9d72bf39f14267a08c28631df24fd9e1d37a3538e39676651556a528e4f3574ca6e597efe3f238a7711d4c81",
          "sha256": "cde472b5390ab4c87875085721838e07741b04bd735b9ded99b9cf5dd573c6c8",
          "sha1": "c0bb9bbb9d4fee69439d48cc45c47347f178060b",
          "md5": "8c62904f226f7927eb4ef3960a688be4"
        }
      ]
    }
  ]
}
