{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix-icons/0.9.0-b9405a6c-SNAPSHOT/miuix-icons-0.9.0-b9405a6c-SNAPSHOT.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix-icons",
    "version": "0.9.0-b9405a6c-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "top.yukonga.miuix.kmp",
          "module": "miuix-core",
          "version": {
            "requires": "0.9.0-b9405a6c-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-icons-mingwX64Main-0.9.0-b9405a6c-SNAPSHOT.klib",
          "url": "miuix-icons-mingwx64-0.9.0-b9405a6c-SNAPSHOT.klib",
          "size": 1309847,
          "sha512": "a02c91e4bfc73727a1fcef2f629dbdab3f67a3780a73480cbb0e051f4af89ad25777112eb6e7542c768641108a1ddce3591089b7e6a1485f8a85409ff1d62f11",
          "sha256": "81b169e57f84bfc0222990d9d570ed8e876fab156328e58f693b03ea1f50511b",
          "sha1": "4db7ebc40bc2e32e65fc771f3aead6f1f64df9ad",
          "md5": "bfd5aa249a12ed79f1b2bbf5527c8934"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-icons-mingwx64-0.9.0-b9405a6c-SNAPSHOT-sources.jar",
          "url": "miuix-icons-mingwx64-0.9.0-b9405a6c-SNAPSHOT-sources.jar",
          "size": 474570,
          "sha512": "ca6d0f65dcc892fe8cf3c7abac7326752104ed06edc4712c5b5c2923084a12472ad43be566560f511062dce52451832f83fc236e45c99f9400ec8ddb4169b2f0",
          "sha256": "174c4b5d2ce06cfd6df963a7e04e00e1226f4a91bb945d3481d0045615494a36",
          "sha1": "24d077628518af64650f4e76dc3be987a7437b8e",
          "md5": "d724d28b678cd422360d76e55bda9e23"
        }
      ]
    },
    {
      "name": "mingwX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "top.yukonga.miuix.kmp",
          "module": "miuix-core",
          "version": {
            "requires": "0.9.0-b9405a6c-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-icons-0.9.0-b9405a6c-SNAPSHOT.kotlin_resources.zip",
          "url": "miuix-icons-mingwx64-0.9.0-b9405a6c-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 354,
          "sha512": "6bb0b574a069d84b24e5a66f9922f5b3618eb1ea305f77b6b1d873209360097866b623549327d9c20a610ef64339375be62372d3273a4677c3c2216439047ec3",
          "sha256": "672571784d477f3ea1fcafc9738994ea2b757887516af94b88f9862096fc6060",
          "sha1": "dd508346dc75c75c4a92257b41feb16cf90d6a19",
          "md5": "b1fc5b76b42f1fd1503471e0b590b11d"
        }
      ]
    }
  ]
}
