{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.11.0-alpha04/foundation-layout-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation-layout",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-mingwX64Main-1.11.0-alpha04.klib",
          "url": "foundation-layout-mingwx64-1.11.0-alpha04.klib",
          "size": 649978,
          "sha512": "c482942226d2078280733cd07b186a8acdcaf451f6b7f589199edfd5d43e8a7e983897627b3028df8aa12026b111bd1864b5e48e532df42d16d22be015c627c4",
          "sha256": "bc4a901ee9f1a9d3b174b39757d982293cd1d44e732b2f2205f4f64472dc6a21",
          "sha1": "45635ebb0718891e4c2bdb4afbc33fe138391658",
          "md5": "643b5cc5dc24983ea40ee62261e9f511"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "foundation-layout-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 140611,
          "sha512": "28775666ee1b25a7a6e7ee7707de20e6f2da0a6f162ca28706f7fa7110b5ef7c5d697960144b89ac61496652f51df56ac3cd2ff4fc8609c8509dac17691420cc",
          "sha256": "c666a96b6400acf073f28bee0654d91c3dc7ab5ebe3976f7f4496d511ff3b9f3",
          "sha1": "01c9f48dcc1d9582abc5ae34d6c58fe307704662",
          "md5": "ae16cb59429146f52b79d28b0e1d867a"
        }
      ]
    }
  ]
}