{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3/1.5.0-alpha13/material3-1.5.0-alpha13.module",
    "group": "org.jetbrains.compose.material3",
    "module": "material3",
    "version": "1.5.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-mingwX64Main-1.5.0-alpha13.klib",
          "url": "material3-mingwx64-1.5.0-alpha13.klib",
          "size": 5155274,
          "sha512": "2c61979318caf488863153afbdace413ed8d24b47afdbdcbba2d6bc0ea254efde579ca438f9c1453a5a700487c852d0442c54cee86f3b4bc9973512a48cf9f4e",
          "sha256": "bce63226197c634bf6294879537edca3720e459540ebc8f58a303862cfff1db1",
          "sha1": "48e0984cece021216f6e8daea228c4841a302d98",
          "md5": "9764bd676a63676c55f5dd2b6db8aa7d"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-mingwx64-1.5.0-alpha13-sources.jar",
          "url": "material3-mingwx64-1.5.0-alpha13-sources.jar",
          "size": 974454,
          "sha512": "76304d4bf8db44ac9dadcfbf4ba84faf384ee7e2d27aef9ec6456e5e77647797bf430399fec3fcaef7b3a0b569410d8b4d88e67910b67642bf7178ed30e06c9b",
          "sha256": "887fe1ccb083eb535dc1839b3c0b507e98bf61e70f60c5e45ebc34cbe67ca441",
          "sha1": "965a84494c6a748535bfe736c602475af90eb33b",
          "md5": "99a778f6e1574107b059543a7fda3ffb"
        }
      ]
    }
  ]
}