{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.11.0-alpha04/ui-util-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-util",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-mingwX64Main-1.11.0-alpha04.klib",
          "url": "ui-util-mingwx64-1.11.0-alpha04.klib",
          "size": 42813,
          "sha512": "6bd510c5685f5ba6a6a1d78b2c9f73a0ade1fb56ee4a50f3b7c6c32c5f18cab1520398225c2583241751cb78a929f88ffaceefb3e5ce52e4f4e5306ebda181cd",
          "sha256": "ff34dbf3ac4905983cb13b76bd0deb17d0884a17d2ed66d9b3c1035a2763a6eb",
          "sha1": "0ac118e7050b09a4df4dd8cd86af243a8c23e697",
          "md5": "b610e2ac942eb2971a2759a454ade1d6"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "ui-util-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 20271,
          "sha512": "3d5d68a47a083265bd1c19da89f37dc77f605402dcfea1802b0badf81b7f3f72796b1a735000a828a44ee3592ac6a9bdea53401d2ce114c7ae88c1f0fbb41b22",
          "sha256": "fa1f447a08be2c7be0f932b7e883eb5b73db7e17dcc0b7c9b187ef7da3faa3a7",
          "sha1": "00f24d4cfacba56a3cb64adcfcac27be1ebbf677",
          "md5": "fbafe82c3fe1b87389b8da5e52ccbb53"
        }
      ]
    }
  ]
}