{
  "formatVersion": "1.1",
  "component": {
    "url": "../../components-resources/1.11.0-alpha04/components-resources-1.11.0-alpha04.module",
    "group": "org.jetbrains.compose.components",
    "module": "components-resources",
    "version": "1.11.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-mingwx64",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-mingwx64",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "components-resources-mingwX64Main-1.11.0-alpha04.klib",
          "url": "components-resources-mingwx64-1.11.0-alpha04.klib",
          "size": 204206,
          "sha512": "867753dfe3c8d33eac8d1cb688234a5d0ca69874ed43a79fb2f6016d2b537028729c7ec4aa3b04670abfefb3cb120b02603dd4a2869cec6ec201ea39311d74fa",
          "sha256": "330c9d91889934adf2d38f48afc2b14dc4a3e82fe4a454a6f5dddc91fb4a7be4",
          "sha1": "73b308d8da2777a31c6b70aef18b30cd81356e50",
          "md5": "e5fd28a4edffb23ba5336380f9d6b3d3"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "components-resources-mingwx64-1.11.0-alpha04-sources.jar",
          "url": "components-resources-mingwx64-1.11.0-alpha04-sources.jar",
          "size": 41247,
          "sha512": "9173a06f9800fd0861629d2f0cb65dae926831fe44e51f2623d48536f015c983ef06dc28221eb9fe66e78c2a72181cd5a07454e73b0308d9f437c278a1fd206c",
          "sha256": "5b67b57c00a090c246cbc1de71725045c65945ec0794bdf0c895f8629e9024c0",
          "sha1": "25b3a5756fc960ba2a201278ba0df2ea505d5a33",
          "md5": "645dfab8d88bef90403654ee32606f7b"
        }
      ]
    }
  ]
}
