{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3/1.5.0-alpha13/material3-1.5.0-alpha13.module",
    "group": "org.jetbrains.compose.material3",
    "module": "material3",
    "version": "1.5.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-mingwX64Main-1.5.0-alpha13.klib",
          "url": "material3-mingwx64-1.5.0-alpha13.klib",
          "size": 5155274,
          "sha512": "2c61979318caf488863153afbdace413ed8d24b47afdbdcbba2d6bc0ea254efde579ca438f9c1453a5a700487c852d0442c54cee86f3b4bc9973512a48cf9f4e",
          "sha256": "bce63226197c634bf6294879537edca3720e459540ebc8f58a303862cfff1db1",
          "sha1": "48e0984cece021216f6e8daea228c4841a302d98",
          "md5": "9764bd676a63676c55f5dd2b6db8aa7d"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha13"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-mingwx64-1.5.0-alpha13-sources.jar",
          "url": "material3-mingwx64-1.5.0-alpha13-sources.jar",
          "size": 974433,
          "sha512": "6ca29101fcebe262c8a699baae5348ad4afb07c325adc879e2d744b26d0c48a613e070d207a357792b4ca0ac57a2136b46369032db8bf47e2ac84d4a57e082c7",
          "sha256": "25b07f667b7b5eab8cea342eb223950b7b8965b9752d797822972302bd38a194",
          "sha1": "d9dce4a3e883906960cc127d9fa898937b5243c8",
          "md5": "64cef063d7f46fac2544933b03bdc179"
        }
      ]
    }
  ]
}